# -*- coding: utf-8 -*-
"""Shared default configuration for MAICA frontends."""

from __future__ import annotations

from typing import Any

from mfocus import DEFAULT_SPECIAL_EVENTS


DEFAULT_CONFIG: dict[str, Any] = {
    "api_base": "https://api.deepseek.com/v1",
    "api_key": "",
    "api_key_required": True,
    "model": "deepseek-chat",
    "temperature": 0.22,
    "top_p": 0.7,
    "max_tokens": 900,
    "frequency_penalty": 0.44,
    "presence_penalty": 0.34,
    "request_timeout": 120,
    "history_messages": 16,
    "memory_limit": 8,
    "language": "en",
    "player_placeholder": "[player]",
    "mfocus_mode": "hybrid",
    "mtrigger_mode": "hybrid",
    "mfocus_sfe_enabled": True,
    "sfe_level": 1,
    "sfe_fact_limit": 14,
    "style_enabled": True,
    "style_db_path": "data/style.db",
    "style_sources": [
        "../MAICA_ds_basis/ds_new.jsonl",
        "../MAICA_ds_basis/moni_dataset_2603.jsonl",
    ],
    "style_example_limit": 3,
    "style_max_source_length": 220,
    "style_import_max_length": 300,
    "anti_grandiosity": True,
    "monika_lens_enabled": True,
    "monika_lens_hint_limit": 2,
    "reflective_lens_enabled": True,
    "reflective_lens_hint_limit": 1,
    "response_planner_enabled": True,
    "response_planner_debug": True,
    "response_planner_examples_enabled": True,
    "response_planner_example_limit": 2,
    "example_bank_enabled": True,
    "example_bank_core_paths": ["data/dialogue_examples_core.jsonl"],
    "example_bank_paths": ["data/dialogue_examples_maica_cleaned.jsonl"],
    "example_bank_limit": 3,
    "example_bank_candidate_limit": 40,
    "example_bank_min_quality": 4,
    "example_bank_min_score": 120,
    "example_bank_max_assistant_length": 220,
    "example_bank_model_filtering": True,
    "example_bank_strict_relevance": False,
    "embedding_enabled": False,
    "embedding_model_path": "../Qwen3-Embedding-0.6B",
    "embedding_device": "cpu",
    "embedding_batch_size": 16,
    "embedding_index_path": "data/example_vectors.faiss",
    "embedding_meta_path": "data/example_vectors_meta.jsonl",
    "embedding_top_k": 30,
    "embedding_min_score": 0.55,
    "example_bank_min_vector_score": 0.62,
    "memory_embedding_enabled": False,
    "memory_embedding_index_path": "data/memory_vectors.faiss",
    "memory_embedding_meta_path": "data/memory_vectors_meta.jsonl",
    "memory_embedding_top_k": 8,
    "memory_embedding_inject_limit": 5,
    "memory_embedding_min_score": 0.55,
    "memory_embedding_fallback_lexical": True,
    "embedding_service_enabled": False,
    "embedding_service_autostart": True,
    "embedding_service_host": "127.0.0.1",
    "embedding_service_port": 8766,
    "embedding_service_timeout": 8,
    "spire_wikipedia_enabled": True,
    "spire_wikipedia_probability": 0.35,
    "spire_wikipedia_language": "en",
    "spire_wikipedia_timeout": 6,
    "spire_reflective_probability": 0.5,
    "spire_recent_topic_window": 8,
    "jsonl_logs_enabled": True,
    "jsonl_logs_path": "logs",
    "database_reset_password": "RESET-MAICA-CLI",
    "show_debug": True,
    "gui_disable_thread_embeddings": True,
    "gui_prewarm_embeddings": False,
    "gui_quiet_embedding_load": True,
    "tts_enabled": False,
    "tts_provider": "windows_sapi",
    "tts_voice": "",
    "tts_auto_play": True,
    "tts_rate": 0,
    "tts_volume": 90,
    "tts_bailian_api_key": "",
    "tts_bailian_endpoint": "wss://dashscope.aliyuncs.com/api-ws/v1/inference",
    "tts_bailian_model": "cosyvoice-v3.5-plus",
    "tts_bailian_voice": "",
    "tts_bailian_format": "mp3",
    "tts_bailian_sample_rate": 22050,
    "tts_bailian_volume": 50,
    "tts_bailian_rate": 1.0,
    "tts_bailian_pitch": 1.0,
    "tts_bailian_timeout": 30,
    "tts_bailian_instruction": "Speak naturally and warmly, like a close daily conversation with a little playful softness.",
    "stt_provider": "windows_speech",
    "stt_language": "en",
    "stt_timeout": 8,
    "special_events": DEFAULT_SPECIAL_EVENTS,
}
