# -*- coding: utf-8 -*-
"""Shared default configuration for MAICA frontends."""

from __future__ import annotations

from typing import Any

from mfocus import DEFAULT_SPECIAL_EVENTS


DEFAULT_CONFIG: dict[str, Any] = {
    "api_base": "https://api.deepseek.com/v1",
    "api_key": "",
    "api_key_required": True,
    "model": "deepseek-chat",
    # LLM call mode: "split" routes agent/tool turns to the agent provider
    # below while casual chat stays on the main provider; "unified" uses the
    # main provider for everything.
    "llm_call_mode": "split",
    "agent_api_base": "",
    "agent_api_key": "",
    "agent_model": "",
    # Agentic tool calling. Off by default: normal chat stays single-shot. When
    # on, a turn may call registered tools in a bounded loop before replying.
    "agent_tools_enabled": False,
    "agent_max_steps": 5,
    "temperature": 0.75,
    "top_p": 0.95,
    "max_tokens": 900,
    "frequency_penalty": 0.12,
    "presence_penalty": 0.08,
    "request_timeout": 120,
    "streaming_enabled": False,
    "history_messages": 16,
    "memory_limit": 8,
    "language": "en",
    "player_placeholder": "[player]",
    "mfocus_mode": "rule",
    "mtrigger_mode": "rule",
    "mfocus_sfe_enabled": True,
    "sfe_level": 1,
    "sfe_fact_limit": 14,
    "style_enabled": True,
    "style_db_path": "data/style.db",
    "style_sources": [
        "../MAICA_ds_basis/ds_new.jsonl",
        "../MAICA_ds_basis/moni_dataset_2603.jsonl",
    ],
    "style_example_limit": 3,
    "style_max_source_length": 220,
    "style_import_max_length": 300,
    "anti_grandiosity": True,
    "monika_lens_enabled": True,
    "monika_lens_hint_limit": 2,
    "reflective_lens_enabled": True,
    "reflective_lens_hint_limit": 1,
    "response_planner_enabled": True,
    "response_planner_mode": "lite",
    "response_planner_debug": True,
    "response_planner_examples_enabled": True,
    "response_planner_example_limit": 3,
    "response_output_mode": "dual",
    "metadata_extract_enabled": True,
    "language_enforce_rewrite": True,
    "example_bank_enabled": True,
    "example_bank_core_paths": ["data/dialogue_examples_core.jsonl"],
    "example_bank_paths": ["data/dialogue_examples_maica_cleaned.jsonl"],
    "example_bank_core_paths_by_language": {
        "en": ["data/dialogue_examples_core.jsonl"],
        "zh": ["data/dialogue_examples_core.jsonl"]
    },
    "example_bank_paths_by_language": {
        "en": ["data/dialogue_examples_en.jsonl"],
        "zh": ["data/dialogue_examples_zh.jsonl"]
    },
    "example_bank_limit": 3,
    "example_bank_candidate_limit": 40,
    "example_bank_min_quality": 4,
    "example_bank_min_score": 150,
    "example_bank_weight": 0.65,
    "example_bank_max_assistant_length": 220,
    "example_bank_model_filtering": True,
    "example_bank_strict_relevance": False,
    "embedding_enabled": False,
    "embedding_model_path": "../Qwen3-Embedding-0.6B",
    "embedding_device": "cpu",
    "embedding_batch_size": 16,
    "embedding_index_path": "data/example_vectors.faiss",
    "embedding_meta_path": "data/example_vectors_meta.jsonl",
    "embedding_top_k": 30,
    "embedding_min_score": 0.55,
    "example_bank_min_vector_score": 0.62,
    "memory_embedding_enabled": False,
    "memory_embedding_index_path": "data/memory_vectors.faiss",
    "memory_embedding_meta_path": "data/memory_vectors_meta.jsonl",
    "memory_embedding_top_k": 8,
    "memory_embedding_inject_limit": 5,
    "memory_embedding_min_score": 0.55,
    "memory_embedding_fallback_lexical": True,
    "embedding_service_enabled": False,
    "embedding_service_autostart": True,
    "embedding_service_host": "127.0.0.1",
    "embedding_service_port": 8766,
    "embedding_service_timeout": 8,
    "spire_wikipedia_enabled": True,
    "spire_wikipedia_probability": 0.35,
    "spire_wikipedia_language": "auto",
    "spire_wikipedia_random_page": True,
    "spire_wikipedia_timeout": 6,
    "spire_reflective_probability": 0.5,
    "spire_recent_topic_window": 8,
    "jsonl_logs_enabled": True,
    "jsonl_logs_path": "logs",
    "database_reset_password": "RESET-MAICA-CLI",
    "auto_backup_enabled": True,
    "auto_backup_keep": 8,
    "auto_memory_summary_enabled": False,
    "auto_memory_summary_turns": 24,
    "auto_memory_summary_min_messages": 8,
    "auto_memory_summary_max_messages": 40,
    "memory_vector_auto_rebuild": True,
    "affection_min": -100.0,
    "affection_max": 10_000.0,
    "affection_daily_positive_cap": 12.0,
    "affection_daily_negative_cap": -12.0,
    "affection_absence_decay_enabled": True,
    "affection_absence_grace_days": 7,
    "affection_absence_daily_decay": 0.25,
    "affection_absence_max_decay": 25.0,
    "affection_event_bonus": 2.0,
    "token_stats_enabled": True,
    "cost_stats_enabled": False,
    "gui_load_recent_messages": 20,
    "gui_idle_spire_enabled": False,
    "gui_idle_spire_minutes": 12,
    "gui_startup_greeting_enabled": True,
    "show_debug": True,
    "gui_disable_thread_embeddings": True,
    "gui_prewarm_embeddings": False,
    "gui_quiet_embedding_load": True,
    "gui_background_mode": "auto",
    "tts_enabled": False,
    "tts_provider": "auto",
    "tts_voice": "",
    "tts_auto_play": True,
    "tts_rate": 0,
    "tts_volume": 90,
    "tts_playback_backend": "auto",
    "tts_playback_command": "",
    "tts_bailian_api_key": "",
    "tts_bailian_endpoint": "wss://dashscope.aliyuncs.com/api-ws/v1/inference",
    "tts_bailian_model": "cosyvoice-v3.5-plus",
    "tts_bailian_voice": "",
    "tts_bailian_format": "mp3",
    "tts_bailian_sample_rate": 22050,
    "tts_bailian_volume": 50,
    "tts_bailian_rate": 1.0,
    "tts_bailian_pitch": 1.0,
    "tts_bailian_timeout": 30,
    "tts_bailian_instruction": "Speak naturally and warmly, like a close daily conversation with a little playful softness.",
    "stt_provider": "auto",
    "stt_language": "en",
    "stt_timeout": 8,
    "stt_bailian_api_key": "",
    "stt_bailian_endpoint": "wss://dashscope.aliyuncs.com/api-ws/v1/inference",
    "stt_bailian_model": "paraformer-realtime-v2",
    "stt_bailian_timeout": 15,
    "special_events": DEFAULT_SPECIAL_EVENTS,
}
